// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by tool/generate_assets.dart

class AppAssets {
  static const String Frame = 'Assets/images/Frame.png';
  static const String Frame2 = 'Assets/images/Frame2.png';
  static const String details1 = 'Assets/images/details1.svg';
  static const String details2 = 'Assets/images/details2.svg';
  static const String details3 = 'Assets/images/details3.svg';
  static const String forgotPassword = 'Assets/images/forgotPassword.png';
  static const String frame3 = 'Assets/images/frame3.png';
  static const String home_icon_active = 'Assets/images/home-icon-active.svg';
  static const String home_icon = 'Assets/images/home-icon.svg';
  static const String menu = 'Assets/images/menu.svg';
  static const String onBoarding = 'Assets/images/onBoarding.png';
  static const String onBoarding1 = 'Assets/images/onBoarding1.png';
  static const String onBoarding2 = 'Assets/images/onBoarding2.png';
  static const String person_active = 'Assets/images/person-active.svg';
  static const String person = 'Assets/images/person.svg';
  static const String search_active = 'Assets/images/search-active.svg';
  static const String search = 'Assets/images/search.svg';
  static const String shopping_cart_active = 'Assets/images/shopping-cart-active.svg';
  static const String shopping_cart = 'Assets/images/shopping-cart.svg';
  static const String succcesOrder = 'Assets/images/succcesOrder.png';
  static const String vector1 = 'Assets/images/vector1.svg';
  static const String vector2 = 'Assets/images/vector2.svg';
}
