// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDMwBn-FumP6ad2aNW297C0vTVWYX0oaUY',
    appId: '1:871715885101:web:46c490b49284a6c122a8a4',
    messagingSenderId: '871715885101',
    projectId: 'dalel-f5413',
    authDomain: 'dalel-f5413.firebaseapp.com',
    storageBucket: 'dalel-f5413.firebasestorage.app',
    measurementId: 'G-K6TC02Y5YY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq4-hXFwrUAxJLpdLTJ8fw0kYAOeYpAhE',
    appId: '1:871715885101:android:5c44f4eaffdb703722a8a4',
    messagingSenderId: '871715885101',
    projectId: 'dalel-f5413',
    storageBucket: 'dalel-f5413.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqsQtUy6ywe4AlmMcUbP2WLKrEgeFiUGM',
    appId: '1:871715885101:ios:e9ac67aa3bf9476a22a8a4',
    messagingSenderId: '871715885101',
    projectId: 'dalel-f5413',
    storageBucket: 'dalel-f5413.firebasestorage.app',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqsQtUy6ywe4AlmMcUbP2WLKrEgeFiUGM',
    appId: '1:871715885101:ios:e9ac67aa3bf9476a22a8a4',
    messagingSenderId: '871715885101',
    projectId: 'dalel-f5413',
    storageBucket: 'dalel-f5413.firebasestorage.app',
    iosBundleId: 'com.example.dalel',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDMwBn-FumP6ad2aNW297C0vTVWYX0oaUY',
    appId: '1:871715885101:web:efe6890eedd533a722a8a4',
    messagingSenderId: '871715885101',
    projectId: 'dalel-f5413',
    authDomain: 'dalel-f5413.firebaseapp.com',
    storageBucket: 'dalel-f5413.firebasestorage.app',
    measurementId: 'G-K3J1XFYG7K',
  );
}
