import 'dart:io';
import 'package:yaml/yaml.dart';

String _toIdentifier(String name) {
  // replace non-alphanumeric with underscore
  var s = name.replaceAll(RegExp(r"[^A-Za-z0-9_]"), '_');
  // if starts with digit, prefix underscore
  if (s.isEmpty) s = 'asset';
  if (RegExp(r'^[0-9]').hasMatch(s)) s = '_$s';
  // ensure no consecutive underscores
  s = s.replaceAll(RegExp(r'_+'), '_');
  return s;
}

void main() {
  final pub = File('pubspec.yaml');
  if (!pub.existsSync()) {
    stderr.writeln('pubspec.yaml not found');
    exit(1);
  }
  final doc = loadYaml(pub.readAsStringSync()) as YamlMap;
  final cfg = doc['flutter_assets'];
  if (cfg == null) {
    stderr.writeln('No `flutter_assets` block found in pubspec.yaml');
    exit(1);
  }
  final assetsPath = cfg['assets_path'] as String?;
  final outputPath = cfg['output_path'] as String?;
  final filename = cfg['filename'] as String?;
  final fieldPrefix = cfg['field_prefix'];
  if (assetsPath == null || outputPath == null || filename == null) {
    stderr.writeln('`flutter_assets` must include `assets_path`, `output_path`, and `filename`');
    exit(1);
  }

  final assetsDir = Directory(assetsPath);
  if (!assetsDir.existsSync()) {
    stderr.writeln('Assets directory not found: $assetsPath');
    exit(1);
  }

  final files = assetsDir
      .listSync(recursive: true)
      .whereType<File>()
      .toList(growable: false);
  files.sort((a, b) => a.path.compareTo(b.path));

  final outDir = Directory(outputPath);
  if (!outDir.existsSync()) outDir.createSync(recursive: true);
  final outFile = File('${outputPath.replaceAll('\\', '/')}${filename}');

  final buffer = StringBuffer();
  buffer.writeln('// GENERATED CODE - DO NOT MODIFY BY HAND');
  buffer.writeln('// Generated by tool/generate_assets.dart');
  buffer.writeln();
  buffer.writeln('class AppAssets {');

  for (final f in files) {
    final rel = f.path.replaceAll('\\', '/');
    // make path relative to project root if it already contains assetsPath
    final assetPath = rel.startsWith(assetsPath) ? rel : rel;
    final name = assetPath.split('/').last.split('.').first;
    final id = _toIdentifier(name);
    final fieldName = (fieldPrefix == null) ? id : '${fieldPrefix}_$id';
    buffer.writeln("  static const String $fieldName = '$assetPath';");
  }

  buffer.writeln('}');

  outFile.writeAsStringSync(buffer.toString());
  stdout.writeln('Generated ${outFile.path} with ${files.length} assets.');
}
